#!/usr/bin/perl

print "Type		Time		Value		Data Center\n";
print "------------------------------------------------------------\n";
while ( <> ) {
	($rtb, $time, $value, $dc) = split;
	if ($value < 0) {
		print "$rtb 	$time	$value	$dc\n";
	}
}
